### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by emj04** [vladimiry/ElectronMail#119]
I receive the error ""Unexpected end of JSON input" when trying to log in to ElectronMail 3.0.0 on Fedora 29.

**Comment by vladimiry** [comment]
Anything in the log file (located in the [setting folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg))?

Try removing/renaming the config.json, setting.bin, database.bin in the settings folder and restarting the app.

PS I've never run Fedora in my life.

**Comment by emj04** [comment]
Removing database.bin fixed it. Thanks =)

This was in the log file:

[2019-03-20 15:35:52.624] [error] Error: Error: net::ERR_NAME_NOT_RESOLVED
    at GitHubProvider.getLatestVersion (/tmp/.mount_electrGLZPqI/resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:39:25)
    at /tmp/.mount_electrGLZPqI/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:346:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_electrGLZPqI/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:335:43)
    at /tmp/.mount_electrGLZPqI/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:362:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/tmp/.mount_electrGLZPqI/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:359:34)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_electrGLZPqI/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at AppImageUpdater.checkForUpdatesAndNotify (/tmp/.mount_electrGLZPqI/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:249:17)
    at Object.t.initAutoUpdate (/tmp/.mount_electrGLZPqI/resources/app.asar/app/webpack:/external "electron-updater":1:1)
    at Object.<anonymous> (/tmp/.mount_electrGLZPqI/resources/app.asar/app/webpack:/src/electron-main/bootstrap/app-ready.ts:32:43)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_electrGLZPqI/resources/app.asar/node_modules/tslib/tslib.js:104:62)
[2019-03-20 15:39:36.214] [error] [pubsub-to-stream-api] provider.error: {"channel":"electron-mail:ipcMain-api","name":"loadDatabase","type":"request","uid":"ffbab01b-ba6e-48a7-a4b5-8e6d359ac1b6"} SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.stringify [as split] (/tmp/.mount_electrHSsbJU/resources/app.asar/app/webpack:/src/electron-main/database/serialization.ts:33:34)
    at t.SerializationAdapter.<anonymous> (/tmp/.mount_electrHSsbJU/resources/app.asar/app/webpack:/src/electron-main/database/serialization.ts:71:37)
    at Generator.next (<anonymous>)
    at /tmp/.mount_electrHSsbJU/resources/app.asar/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/tmp/.mount_electrHSsbJU/resources/app.asar/node_modules/tslib/tslib.js:103:16)
    at t.SerializationAdapter.length [as read] (/tmp/.mount_electrHSsbJU/resources/app.asar/app/webpack:/src/electron-main/database/serialization.ts:65:60)
    at h.<anonymous> (/tmp/.mount_electrHSsbJU/resources/app.asar/app/webpack:/src/electron-main/database/index.ts:169:13)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_electrHSsbJU/resources/app.asar/node_modules/tslib/tslib.js:104:62

[2019-03-20 15:39:36.383] [error] [reducers/errors] <angular> { message: 'Unexpected end of JSON input', name: 'SyntaxError' }

**Comment by vladimiry** [comment]
I just realized that I missed re-implementing atomic file writing after the database serialization refactoring. This is a huge flaw since database.bin can be easily corrupted for example by abnormal program exit during database file writing. I guess this is what was a cause of the issue.

**Comment by vladimiry** [comment]
Atomic writing fix is included in just published v3.0.1 release.
