### ISSUE TITLE
ElectronMail error after login

### ISSUE THREAD

**Issue by fire-pig** [vladimiry/ElectronMail#145]
OS:  Mac OS X Mojave
Accounts:  15 Protonmail accounts

After entering login for app, accounts appear, but the following message appears before any of them are opened.  None of them are opened when I click on them.  

Thank you! 

Unhandled Promise Rejection
Error: Failed index emails in 15000ms (mails portions size: 933)
    at MergeMapSubscriber.IPC_MAIN_API_DB_INDEXER_NOTIFICATION$ [as project] (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/webpack:/src/electron-main/api/endpoints-builders/database/indexing.ts:85:5)
    at MergeMapSubscriber._tryNext (/Applications/ElectronMail.app/Contents/Resources/app.asar/node_modules/rxjs/src/internal/operators/mergeMap.ts:135:21)
    at MergeMapSubscriber._next (/Applications/ElectronMail.app/Contents/Resources/app.asar/node_modules/rxjs/src/internal/operators/mergeMap.ts:125:12)
    at MergeMapSubscriber.Subscriber.next (/Applications/ElectronMail.app/Contents/Resources/app.asar/node_modules/rxjs/src/internal/Subscriber.ts:99:12)
    at AsyncAction.dispatch (/Applications/ElectronMail.app/Contents/Resources/app.asar/node_modules/rxjs/src/internal/observable/timer.ts:91:14)
    at AsyncAction._execute (/Applications/ElectronMail.app/Contents/Resources/app.asar/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:122:12)
    at AsyncAction.execute (/Applications/ElectronMail.app/Contents/Resources/app.asar/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:97:24)
    at AsyncScheduler.flush (/Applications/ElectronMail.app/Contents/Resources/app.asar/node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:58:26)

**Comment by vladimiry** [comment]
Can you increse the `timeouts.indexingBootstrap` value in the `config.json` file which is located in the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg)? Then restart the app.

**Comment by fire-pig** [comment]
Thanks for the suggestion!  That worked.  I updated two settings, webViewApiPing, and indexingBootstrap.  I also upgraded to the latest pre-release builds.  Here's what my timeouts section looks like now. 

  "timeouts": {
    "dbBootstrapping": 43200000,
    "dbSyncing": 1800000,
    "webViewApiPing": 150000,
    "domElementsResolving": 20000,
    "defaultApiCall": 25000,
    "databaseLoading": 300000,
    "indexingBootstrap": 500000
  },

**Comment by vladimiry** [comment]
Ok. Closing the issue then.

I try to keep the working for average case default timeouts and 15 accounts case certainly doesn't look like an average case. But I will consider increasing some default timeouts or maybe adding FAQ section in the readme that will cover most popular questions and tricky use cases, see #146.

**Comment by fire-pig** [comment]
Thanks!  FWIW, I have so many accounts because I create a new email for different services.  So that if one service is compromised, it can't be linked to other services by the email address.  So I typically don't have need to login to them that frequently.    However, Protonmail and Tutanota say they will delete accounts that aren't logged into every 3-6 months, so I need a way to login to them easily occasionally.  Hence, why Electronmail is so useful, because it logs in automatically.

**Comment by vladimiry** [comment]
> Protonmail and Tutanota say they will delete accounts that aren't logged into every 3-6 months

As far as I know, Protonmail says so but has never yet applied this policy to anyone but they reserve the right to do so in the future. Nont aware of khow these things work with Tutanota.

You can, by the way, set a signing random delay range for the accounts you don't need to login immediately with app start as I believe that might improve signing into the primary accounts, see details here https://github.com/vladimiry/ElectronMail/releases/tag/v3.1.0 and in #121. For you case delay probably could be set to big value.

**Comment by fire-pig** [comment]
Ah, thanks!  You're right, those features would likely be useful for many of my accounts.
