### ISSUE TITLE
Invocation timeout of calling "notification" method on "electron-mail:webview-api" channel with 25000ms timeout

### ISSUE THREAD

**Issue by lachlantula** [vladimiry/ElectronMail#252]
Hi,
I'm having issues with the latest version of ElectronMail from the AUR (4.2.2-1). I use the package `electronmail-bin` and receive the error `Invocation timeout of calling "notification" method on "electron-mail:webview-api" channel with 25000ms timeout`. This error appears after unlocking the application, and I'm then lead to a grey screen which shows the error.

![image](https://user-images.githubusercontent.com/12870244/74431105-6393d780-4eb2-11ea-9925-ee7b5749069b.png)

This version has proven to be buggy to me in a few different ways; sometimes the entire application goes completely white - not just the frame in which ProtonMail sits - following an attempted autologin.

My `log.log` file reads as follows:

```
[2019-08-01 00:38:06.608] [error] [src/electron-main/api/index] [pubsub-to-rpc-api] [provider] notification.error DecryptionError: Decryption failed ({"type":"sodium.crypto_secretbox_easy","options":{"nonceBytes":24},"data":{"nonceBase64":"H5Z+e53xeW4bt1HC8RYA97UPTHymgr+g"}})
    at Object.<anonymous> (/opt/ElectronMail/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:52:35)
    at step (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:136:27)
    at Object.throw (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:117:57)
    at rejected (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:108:69) {"name":"readSettings","channel":"electron-mail:ipcMain-api","payloadType":"request","uid":"d582b4ac-a821-42b6-9660-cc6e88b1f1c3"}
[2019-08-01 00:38:06.610] [error] [reducers/notification] <angular> { name: 'DecryptionError',
  message: 'Failed to decrypt the settings storage',
  stack:
   'DecryptionError: Decryption failed ({"type":"sodium.crypto_secretbox_easy","options":{"nonceBytes":24},"data":{"nonceBase64":"H5Z+e53xeW4bt1HC8RYA97UPTHymgr+g"}})\n    at Object.<anonymous> (/opt/ElectronMail/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:52:35)\n    at step (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:136:27)\n    at Object.throw (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:117:57)\n    at rejected (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:108:69)' }
[2019-09-23 23:11:40.143] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-09-25 17:04:07.900] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-09-25 17:04:43.782] [error] [WEBVIEW:protonmail] [api/index] [pubsub-to-rpc-api] [provider] notification.error Error {} {"name":"login2fa","channel":"electron-mail:webview-api","payloadType":"request","uid":"3fb7ddae-477a-4883-851a-7b3eab5c122d"}
[2019-09-25 17:04:43.794] [error] [reducers/notification] <angular> {
  name: 'Error',
  message: 'Failed to submit two factor token within 8000ms',
  stack: 'Error: Failed to submit two factor token ' +
    'within 8000ms\n    at submit ' +
    '(<anonymous>:25471:19)'
}
[2019-09-25 17:14:37.153] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-09-25 17:15:12.726] [error] [WEBVIEW:protonmail] [api/index] [pubsub-to-rpc-api] [provider] notification.error Error {} {"name":"login2fa","channel":"electron-mail:webview-api","payloadType":"request","uid":"e9218a0b-5eae-4faf-9daf-160a39e1ab23"}
[2019-09-25 17:15:12.737] [error] [reducers/notification] <angular> {
  name: 'Error',
  message: 'Failed to submit two factor token within 8000ms',
  stack: 'Error: Failed to submit two factor token ' +
    'within 8000ms\n    at submit ' +
    '(<anonymous>:25471:19)'
}
[2019-09-25 17:15:38.277] [error] [reducers/notification] <angular> {
  name: 'Error',
  message: 'Failed to submit two factor token within 8000ms',
  stack: 'Error: Failed to submit two factor token ' +
    'within 8000ms\n    at submit ' +
    '(<anonymous>:25471:19)'
}
[2019-09-25 17:15:38.278] [error] [WEBVIEW:protonmail] [api/index] [pubsub-to-rpc-api] [provider] notification.error Error {} {"name":"login2fa","channel":"electron-mail:webview-api","payloadType":"request","uid":"7aa4ad9b-ba5a-4222-8a3a-ffe103a59234"}
[2019-09-25 17:17:29.082] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-09-25 17:17:51.731] [error] [reducers/notification] <angular> {
  name: 'Error',
  message: "It's not allowed to submit the same password for the same account more " +
    'than 2 times per 10 seconds (page type: "login2fa"). Make sure that ' +
    'your password is valid. Auto login feature is disable until app ' +
    'restarted.',
  stack: "Error: It's not allowed to submit the same password for the same account " +
    'more than 2 times per 10 seconds (page type: "login2fa"). Make sure that ' +
    'your password is valid. Auto login feature is disable until app ' +
    'restarted.\n    at rateLimitCheck ' +
    '(file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.js?6a7500e09d79549ae479:1924:27)\n' +
    '    at MergeMapSubscriber.project ' +
    '(file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.js?6a7500e09d79549ae479:2044:21)\n' +
    '    at ' +
    'MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext ' +
    '(file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?6a7500e09d79549ae479:106775:27)\n' +
    '    at ' +
    'MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next ' +
    '(file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?6a7500e09d79549ae479:106765:18)\n' +
    '    at ' +
    'MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next ' +
    '(file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?6a7500e09d79549ae479:104158:18)\n' +
    '    at ' +
    'MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next ' +
    '(file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?6a7500e09d79549ae479:106622:26)\n' +
    '    at ' +
    'MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next ' +
    '(file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?6a7500e09d79549ae479:104158:18)\n' +
    '    at ' +
    'FilterSubscriber.push../node_modules/rxjs/_esm5/internal/operators/filter.js.FilterSubscriber._next ' +
    '(file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?6a7500e09d79549ae479:106238:30)\n' +
    '    at ' +
    'FilterSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next ' +
    '(file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?6a7500e09d79549ae479:104158:18)\n' +
    '    at ' +
    'ScannedActionsSubject.push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next ' +
    '(file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?6a7500e09d79549ae479:103934:25)'
}
[2019-09-25 17:18:00.751] [error] [WEBVIEW:protonmail] [api/index] [pubsub-to-rpc-api] [provider] notification.error Error {} {"name":"login2fa","channel":"electron-mail:webview-api","payloadType":"request","uid":"e3c1f3eb-86f3-4715-8ba8-b7dcfa139d98"}
[2019-09-25 17:18:05.229] [error] [WEBVIEW:protonmail] [api/index] [pubsub-to-rpc-api] [provider] notification.error Error {} {"name":"login2fa","channel":"electron-mail:webview-api","payloadType":"request","uid":"cb0815f6-7091-40db-b278-3982ae107056"}
[2019-09-25 17:33:53.521] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-09-25 17:34:26.782] [error] [WEBVIEW:protonmail] [api/index] [pubsub-to-rpc-api] [provider] notification.error Error {} {"name":"login2fa","channel":"electron-mail:webview-api","payloadType":"request","uid":"68a71e98-dd7a-47e2-9dc6-13e5afe1de61"}
[2019-09-25 17:34:26.793] [error] [reducers/notification] <angular> {
  name: 'Error',
  message: 'Failed to submit two factor token within 8000ms',
  stack: 'Error: Failed to submit two factor token ' +
    'within 8000ms\n    at submit ' +
    '(<anonymous>:25471:19)'
}
[2019-09-26 10:24:21.693] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-09-27 20:26:35.897] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-09-30 17:25:41.581] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-10-01 20:35:37.237] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-10-02 00:48:13.170] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-10-02 10:13:00.721] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-10-11 23:03:06.960] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-10-12 13:53:17.701] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-10-13 23:20:46.075] [error] [src/electron-main/api/index] "keytar" module is unsupported by the system Error: The name org.freedesktop.secrets was not provided by any .service files
[2019-12-17 23:56:40.114] [error] [src/electron-main/api/index] [pubsub-to-rpc-api] [provider] notification.error DecryptionError: Decryption failed ({"type":"sodium.crypto_secretbox_easy","options":{"nonceBytes":24},"data":{"nonceBase64":"H5Z+e53xeW4bt1HC8RYA97UPTHymgr+g"}})
    at Object.<anonymous> (/opt/ElectronMail/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:52:35)
    at step (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:136:27)
    at Object.throw (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:117:57)
    at rejected (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:108:69) {"name":"readSettings","channel":"electron-mail:ipcMain-api","payloadType":"request","uid":"df978ab5-3e83-40a3-bacd-183cabc6361c"}
[2019-12-17 23:56:40.117] [error] [reducers/notification] <angular> {
  name: 'DecryptionError',
  message: 'Failed to decrypt the settings storage',
  stack: 'DecryptionError: Decryption failed ' +
    '({"type":"sodium.crypto_secretbox_easy","options":{"nonceBytes":24},"data":{"nonceBase64":"H5Z+e53xeW4bt1HC8RYA97UPTHymgr+g"}})\n' +
    '    at Object.<anonymous> ' +
    '(/opt/ElectronMail/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:52:35)\n' +
    '    at step ' +
    '(/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:136:27)\n' +
    '    at Object.throw ' +
    '(/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:117:57)\n' +
    '    at rejected ' +
    '(/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:108:69)'
}
[2019-12-19 12:48:16.209] [error] [src/electron-main/api/index] [pubsub-to-rpc-api] [provider] notification.error DecryptionError: Decryption failed ({"type":"sodium.crypto_secretbox_easy","options":{"nonceBytes":24},"data":{"nonceBase64":"H5Z+e53xeW4bt1HC8RYA97UPTHymgr+g"}})
    at Object.<anonymous> (/opt/ElectronMail/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:52:35)
    at step (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:136:27)
    at Object.throw (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:117:57)
    at rejected (/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:108:69) {"name":"readSettings","channel":"electron-mail:ipcMain-api","payloadType":"request","uid":"4b1f28b7-8067-46fc-a9d9-9635c00b5879"}
[2019-12-19 12:48:16.211] [error] [reducers/notification] <angular> {
  name: 'DecryptionError',
  message: 'Failed to decrypt the settings storage',
  stack: 'DecryptionError: Decryption failed ' +
    '({"type":"sodium.crypto_secretbox_easy","options":{"nonceBytes":24},"data":{"nonceBase64":"H5Z+e53xeW4bt1HC8RYA97UPTHymgr+g"}})\n' +
    '    at Object.<anonymous> ' +
    '(/opt/ElectronMail/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:52:35)\n' +
    '    at step ' +
    '(/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:136:27)\n' +
    '    at Object.throw ' +
    '(/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:117:57)\n' +
    '    at rejected ' +
    '(/opt/ElectronMail/resources/app.asar/node_modules/tslib/tslib.js:108:69)'
}
[2020-01-21 17:14:33.767] [error] [WEBVIEW:protonmail] [api/index] [pubsub-to-rpc-api] [provider] notification.error Error {} {"name":"login2fa","channel":"electron-mail:webview-api","payloadType":"request","uid":"e5336251-3e2a-445c-aadd-ea06eac9d134"}
[2020-01-21 17:14:33.782] [error] [reducers/notification] <angular> {
  name: 'Error',
  message: 'Failed to submit two factor token within 8000ms',
  stack: 'Error: Failed to submit two factor token ' +
    'within 8000ms\n    at submit ' +
    '(<anonymous>:26958:19)'
}
[2020-02-12 23:45:22.790] [error] [reducers/notification] <angular> {
  name: 'Error',
  message: 'Invocation timeout of calling "login" method on "electron-mail:webview-api" channel with 25000ms timeout',
  stack: 'Error: Invocation timeout of calling "login" method on "electron-mail:webview-api" channel with 25000ms timeout\n' +
    '    at MergeMapSubscriber.project (<anonymous>:1258:42)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (<anonymous>:7632:27)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (<anonymous>:7622:18)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (<anonymous>:5968:18)\n' +
    '    at AsyncAction.dispatch (<anonymous>:6963:16)\n' +
    '    at AsyncAction../node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js.AsyncAction._execute (<anonymous>:8126:18)\n' +
    '    at AsyncAction../node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js.AsyncAction.execute (<anonymous>:8114:26)\n' +
    '    at AsyncScheduler../node_modules/rxjs/_esm5/internal/scheduler/AsyncScheduler.js.AsyncScheduler.flush (<anonymous>:8211:32)\n' +
    '    at ZoneDelegate.invokeTask (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?fe8bf46373ccdf48845b:103895:35)\n' +
    '    at Object.onInvokeTask (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?fe8bf46373ccdf48845b:43435:33)'
}
[2020-02-12 23:45:29.908] [error] [reducers/notification] <angular> {
  name: 'Error',
  message: 'Invocation timeout of calling "login2fa" method on "electron-mail:webview-api" channel with 25000ms timeout',
  stack: 'Error: Invocation timeout of calling "login2fa" method on "electron-mail:webview-api" channel with 25000ms timeout\n' +
    '    at MergeMapSubscriber.project (<anonymous>:1258:42)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (<anonymous>:7632:27)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (<anonymous>:7622:18)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (<anonymous>:5968:18)\n' +
    '    at AsyncAction.dispatch (<anonymous>:6963:16)\n' +
    '    at AsyncAction../node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js.AsyncAction._execute (<anonymous>:8126:18)\n' +
    '    at AsyncAction../node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js.AsyncAction.execute (<anonymous>:8114:26)\n' +
    '    at AsyncScheduler../node_modules/rxjs/_esm5/internal/scheduler/AsyncScheduler.js.AsyncScheduler.flush (<anonymous>:8211:32)\n' +
    '    at ZoneDelegate.invokeTask (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?fe8bf46373ccdf48845b:103895:35)\n' +
    '    at Object.onInvokeTask (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?fe8bf46373ccdf48845b:43435:33)'
}
[2020-02-13 18:58:53.008] [error] [reducers/notification] <angular> {
  name: 'Error',
  message: 'Invocation timeout of calling "notification" method on "electron-mail:webview-api" channel with 25000ms timeout',
  stack: 'Error: Invocation timeout of calling "notification" method on "electron-mail:webview-api" channel with 25000ms timeout\n' +
    '    at MergeMapSubscriber.project (<anonymous>:1258:42)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (<anonymous>:7632:27)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (<anonymous>:7622:18)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (<anonymous>:5968:18)\n' +
    '    at AsyncAction.dispatch [as work] (<anonymous>:6963:16)\n' +
    '    at AsyncAction../node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js.AsyncAction._execute (<anonymous>:8126:18)\n' +
    '    at AsyncAction../node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js.AsyncAction.execute (<anonymous>:8114:26)\n' +
    '    at AsyncScheduler../node_modules/rxjs/_esm5/internal/scheduler/AsyncScheduler.js.AsyncScheduler.flush (<anonymous>:8211:32)\n' +
    '    at ZoneDelegate.invokeTask (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?52d3a1d7470e49f3b30c:103895:35)\n' +
    '    at Object.onInvokeTask (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?52d3a1d7470e49f3b30c:43435:33)'
}
[2020-02-13 22:43:45.686] [error] [reducers/notification] <angular> {
  name: 'Error',
  message: 'Invocation timeout of calling "notification" method on "electron-mail:webview-api" channel with 25000ms timeout',
  stack: 'Error: Invocation timeout of calling "notification" method on "electron-mail:webview-api" channel with 25000ms timeout\n' +
    '    at MergeMapSubscriber.project (<anonymous>:1258:42)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (<anonymous>:7632:27)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (<anonymous>:7622:18)\n' +
    '    at MergeMapSubscriber../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (<anonymous>:5968:18)\n' +
    '    at AsyncAction.dispatch [as work] (<anonymous>:6963:16)\n' +
    '    at AsyncAction../node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js.AsyncAction._execute (<anonymous>:8126:18)\n' +
    '    at AsyncAction../node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js.AsyncAction.execute (<anonymous>:8114:26)\n' +
    '    at AsyncScheduler../node_modules/rxjs/_esm5/internal/scheduler/AsyncScheduler.js.AsyncScheduler.flush (<anonymous>:8211:32)\n' +
    '    at ZoneDelegate.invokeTask (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?52d3a1d7470e49f3b30c:103895:35)\n' +
    '    at Object.onInvokeTask (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/vendor.js?52d3a1d7470e49f3b30c:43435:33)'
}
```

I'd be happy to try further diagnose this, I'm just not too sure where to start. Cheers!

**Comment by vladimiry** [comment]
You started facing the issue just recently (like 1-2 days back) or from the first 4.2.2 start?

**Comment by vladimiry** [comment]
> Invocation timeout of calling "notification" method on "electron-mail:webview-api" channel with 25000ms timeout

In general, the issue looks very similar to what we went through in recently resolved #250. So I'd suggest you try [the most recent build](https://mega.nz/#F!I4Q2XI5D!POQ7hlTR2HtrZRZeBR2mHA) assembled from the master branch with the #250 - related changes included (disabling the `backgroundThrottling` flag for @electron)   upgrade to @electron 7.1.10 => 8.0.0.

The app itself is a static thing. It doesn't update itself. The issue started to happen for Arch Linux based distro users 1-2 days ago. So I guess some Arch/system update somehow affected the app behavior in the way so communication between the app renderer process and the webview process got broken. See more details in https://github.com/vladimiry/ElectronMail/issues/250#issuecomment-585443624.

**Comment by vladimiry** [comment]
@lachlantula, can you show the `uname -a` output? I'm wondering is it `5.5.x` kernel version.

**Comment by lachlantula** [comment]
> You started facing the issue just recently (like 1-2 days back) or from the first 4.2.2 start when it got released?

I wouldn't know for certain, apologies; I've been away from my desktop for a little while and haven't had a chance to use EM. I believe the issue started occurring once I updated to 4.2.2.

> ...I'd suggest you try [the most recent build](https://mega.nz/#F!I4Q2XI5D!POQ7hlTR2HtrZRZeBR2mHA) assembled from the master branch with the #250 - related changes included (disabling the `backgroundThrottling` flag for @electron) upgrade to @electron 7.1.10 => 8.0.0.

Trying the new AppImage seems to be working for me. If you'd like any logs regarding this update I'd be happy to provide. 

> @lachlantula, can you show the `uname -a` output? I'm wondering is it `5.5.x` kernel version.

Yeah, I'm on 5.5.3-arch1-1. Thanks for the help!

**Comment by vladimiry** [comment]
> Trying the new AppImage seems to be working for me. If you'd like any logs regarding this update I'd be happy to provide.

Can you also try pacman build (you originally specified that you use AUR, so pacman build)? Get it by the same link https://mega.nz/#F!I4Q2XI5D!POQ7hlTR2HtrZRZeBR2mHA

If pacman build works well then I'm going to close this issue but will keep tracking a weird app behavior on Arch-based systems in #253.

**Comment by lachlantula** [comment]
Pleased to report that the Pacman build gives the same behaviour as the AppImage.
