### ISSUE TITLE
error: Invalid URL protocol, when accessing ProtonDrive

### ISSUE THREAD

**Issue by edmundlaugasson** [vladimiry/ElectronMail#386]
Using ElectronMail 4.11.0 (Flatpak). When opening ProtonDrive, the following error appears:
```
Unhandled Error
TypeError: Invalid URL protocol
    at default_1.parse (/app/ElectronMail/resources/app.asar/node_modules/@cliqz/url-parser/build/cjs/lib/immutable-url.js:420:23)
    at new default_1 (/app/ElectronMail/resources/app.asar/node_modules/@cliqz/url-parser/build/cjs/lib/immutable-url.js:54:14)
    at new default_1 (/app/ElectronMail/resources/app.asar/node_modules/@cliqz/url-parser/build/cjs/lib/url.js:41:20)
    at Object.depersonalizeProtonApiUrl (/app/ElectronMail/resources/app.asar/app/electron-main.js:7452:10)
    at replacer (/app/ElectronMail/resources/app.asar/app/electron-main.js:7469:41)
    at String.replace (<anonymous>)
    at Object.result [as depersonalizeLoggedUrlsInString] (/app/ElectronMail/resources/app.asar/app/electron-main.js:7470:37)
    at Object.<anonymous> (/app/ElectronMail/resources/app.asar/app/electron-main.js:5499:147)
```

I understand, that ProtonDrive is for invited users only for now, but it should announce it without such an error. This error appears before that invited users only message comes.
I remember, that with earlier versions of ElectronMail, I didn't see such an error.

**Comment by vladimiry** [comment]
This is a good finding. Should be fixed by f82f407ad320eccfc7ecc95ea4976c9c0b51f842. Not promising but a new release might come at the end of the week.

>  I remember, that with earlier versions of ElectronMail, I didn't see such an error.

The bug was introduced just recently in an attempt to make logged URLs parsed from the raw errors/data more private.
