### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by alx-xlx** [vladimiry/ElectronMail#408]
Unhandled Error
Error: ENOENT, app/assets/icons/icon.png not found in C:/Program Files/ElectronMail/resources/app.asar
    at createError (electron/js2c/asar_bundle.js:5:1289)
    at Object.t.<computed> [as open] (electron/js2c/asar_bundle.js:5:2560)
    at Object.trayIconBundleFromPath (C:/Program Files/ElectronMail/resources/app.asar/app/electron-main.js:2012:63)
    at resultFn (C:/Program Files/ElectronMail/resources/app.asar/app/electron-main.js:1827:38)
    at Object.updateOverlayIcon (C:/Program Files/ElectronMail/resources/app.asar/app/electron-main.js:1849:33)
    at IpcMainImpl.listenerSubscriptionArgs (C:/Program Files/ElectronMail/resources/app.asar/node_modules/pubsub-to-rpc-api/lib/service/provider.js:67:47)

**Comment by vladimiry** [comment]
What is the way you installed the app (download link)?
