### ISSUE TITLE
Does not work with Whonix

### ISSUE THREAD

**Issue by clayt0nk** [vladimiry/ElectronMail#432]
Version 4.12.5 installed with Flatpak

I have two pm accounts. ElectronMail was flawlessly reliable with both up until a few days ago. Then one of them (not always the same one, but always one of them) failed to work. Today both fail to work. Below is a sample of the errors I am getting.

```
Uncaught (in promise): Error: Failed to load "webclient0://app.protonmail.ch/blank.html?loader-id=01c3021a-9aaf-4c97-b9ed-25f07fdbeba2" page in 15000ms

Error: Failed to load "webclient0://app.protonmail.ch/blank.html?loader-id=01c3021a-9aaf-4c97-b9ed-25f07fdbeba2" page in 15000ms

at CoreService.<anonymous> (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.js:72264:21)

at Generator.throw (<anonymous>)

at rejected (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.js:69189:38)

at ZoneDelegate.invoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.js:69687:166)

at Object.onInvoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.js:21665:33)

at ZoneDelegate.invoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.js:69687:54)

at Zone.run (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.js:69502:43)

at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.js:70334:34

at ZoneDelegate.invokeTask (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.js:69702:179)

at Object.onInvokeTask (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.js:21656:33)
```

**Comment by vladimiry** [comment]
Looks like a similar to placed before #311 and #349 issues solution for which was in updating the `flatpak` thing in the system.

The app was not updated and it's not @protonmail API error (@protonmail stuff didn't yet come into the game at this stage), so something changed in your system.

**Comment by clayt0nk** [comment]
Yes, you are right. So when it was working before, it was in an Archlinux VM behind Tor. It is currently working again in a Debian VM without Tor. The environment that did not work yesterday is Whonix Workstation VM (also behind Tor, but Tor itself is not the problem per the first case). So something that Whonix Workstation (which bends over backwards to ensure that ZERO network traffic can leak out of the Tor tunnel) does interferes with the functioning of this app.

**Comment by ew0k** [comment]
Hey clayt0nk, why don't you install the debian package?

**Comment by clayt0nk** [comment]
On Wed, 29 Sep 2021 16:15:24 +0000 (UTC)
ew0k ***@***.***> wrote:

> Hey clayt0nk, why don't you install the debian package? 

Fair question: because I see no sign of an ElectronMail Debian
repository. Without that, updates are a repetitive manual nauz that I
really try to avoid. I spend too much time keeping my QubesOS
installation up-to-date as it is. Flatpak updates everything installed
with one keypress.

I might have tried the snap package, but in my experience snaps do not
work reliably on QubesOS.

-- 
Clayton ***@***.***>
Size limit 4M. Please send large attachments to ***@***.***

**Comment by vladimiry** [comment]
Moved to #559.
