### ISSUE TITLE
Hang when opening app with incoming mails on two accounts

### ISSUE THREAD

**Issue by Tibladar** [vladimiry/ElectronMail#467]
ElectronMail hangs when opening and receiving an email in two accounts:
`Invocation timeout of calling "updateOverlayIcon" method on "electron-mail:ipcMain-api" channel with 25000ms timeout`

![image](https://user-images.githubusercontent.com/52620063/143580486-3a564594-45e8-464f-a600-62574e5ab662.png)

## Steps to reproduce
- You need to have (at least) two different accounts in ElectronMail
- Close ElectronMail
- Send an email (e.g. via web-interface) to both of your accounts
- Open ElectronMail
- See it hanging

## Info
Package Type: Flatpak
Package Version: 4.13.1
Local storage used: No

Desktop environment: Cinnamon
OS: Linux Mint 20.2

<details><summary>log.log file</summary>

```
[2021-11-26 13:04:05.535] [error] src/electron-main/web-contents.ts {"level":3,"message":"[object Object]","line":33094,"sourceId":"file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs"}
[2021-11-26 13:04:05.538] [error] src/electron-main/web-contents.ts {"level":3,"message":"[object Object]","line":33094,"sourceId":"file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs"}
[2021-11-26 13:04:05.538] [error] src/electron-main/web-contents.ts {"level":3,"message":"[object Object]","line":33094,"sourceId":"file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs"}
[2021-11-26 13:04:05.549] [error] src/web/browser-window/app/app.error-handler.service.ts {
  name: 'Error',
  message: 'Uncaught (in promise): Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).\n' +
    'Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).\n' +
    '    at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:32449:47\n' +
    '    at doInnerSub (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:26214:68)\n' +
    '    at outerNext (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:26208:38)\n' +
    '    at OperatorSubscriber._this._next (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24953:13)\n' +
    '    at OperatorSubscriber.Subscriber.next (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24079:97)\n' +
    '    at AsyncAction.<anonymous> (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24880:24)\n' +
    '    at AsyncAction._execute (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28071:16)\n' +
    '    at AsyncAction.execute (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28064:26)\n' +
    '    at AsyncScheduler.flush (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28121:30)\n' +
    '    at args.<computed> (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:31371:37)',
  stack: 'Error: Uncaught (in promise): Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).\n' +
    'Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).\n' +
    '    at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:32449:47\n' +
    '    at doInnerSub (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:26214:68)\n' +
    '    at outerNext (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:26208:38)\n' +
    '    at OperatorSubscriber._this._next (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24953:13)\n' +
    '    at OperatorSubscriber.Subscriber.next (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24079:97)\n' +
    '    at AsyncAction.<anonymous> (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24880:24)\n' +
    '    at AsyncAction._execute (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28071:16)\n' +
    '    at AsyncAction.execute (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28064:26)\n' +
    '    at AsyncScheduler.flush (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28121:30)\n' +
    '    at args.<computed> (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:31371:37)\n' +
    '    at resolvePromise (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:30296:25)\n' +
    '    at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:30234:15\n' +
    '    at asyncGeneratorStep (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:67139:9)\n' +
    '    at _throw (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:67153:13)\n' +
    '    at ZoneDelegate.invoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29691:164)\n' +
    '    at Object.onInvoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:53558:29)\n' +
    '    at ZoneDelegate.invoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29691:52)\n' +
    '    at Zone.run (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29506:41)\n' +
    '    at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:30338:32\n' +
    '    at ZoneDelegate.invokeTask (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29706:177)'
}
[2021-11-26 13:04:05.550] [error] src/web/browser-window/app/app.error-handler.service.ts {
  message: 'Uncaught (in promise): Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).\n' +
    'Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).\n' +
    '    at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:32449:47\n' +
    '    at doInnerSub (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:26214:68)\n' +
    '    at outerNext (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:26208:38)\n' +
    '    at OperatorSubscriber._this._next (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24953:13)\n' +
    '    at OperatorSubscriber.Subscriber.next (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24079:97)\n' +
    '    at AsyncAction.<anonymous> (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24880:24)\n' +
    '    at AsyncAction._execute (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28071:16)\n' +
    '    at AsyncAction.execute (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28064:26)\n' +
    '    at AsyncScheduler.flush (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28121:30)\n' +
    '    at args.<computed> (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:31371:37)',
  name: 'Error',
  stack: 'Error: Uncaught (in promise): Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).\n' +
    'Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).\n' +
    '    at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:32449:47\n' +
    '    at doInnerSub (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:26214:68)\n' +
    '    at outerNext (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:26208:38)\n' +
    '    at OperatorSubscriber._this._next (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24953:13)\n' +
    '    at OperatorSubscriber.Subscriber.next (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24079:97)\n' +
    '    at AsyncAction.<anonymous> (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:24880:24)\n' +
    '    at AsyncAction._execute (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28071:16)\n' +
    '    at AsyncAction.execute (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28064:26)\n' +
    '    at AsyncScheduler.flush (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:28121:30)\n' +
    '    at args.<computed> (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:31371:37)\n' +
    '    at resolvePromise (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:30296:25)\n' +
    '    at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:30234:15\n' +
    '    at asyncGeneratorStep (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:67139:9)\n' +
    '    at _throw (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:67153:13)\n' +
    '    at ZoneDelegate.invoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29691:164)\n' +
    '    at Object.onInvoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:53558:29)\n' +
    '    at ZoneDelegate.invoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29691:52)\n' +
    '    at Zone.run (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29506:41)\n' +
    '    at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:30338:32\n' +
    '    at ZoneDelegate.invokeTask (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29706:177)'
}
[2021-11-26 13:04:05.551] [error] src/web/browser-window/app/app.error-handler.service.ts {
  name: 'Error',
  message: 'Uncaught (in promise): Error: Invocation timeout of calling "resolveLiveProtonClientSession" method on "electron-mail:webview-api:primary" channel with 25000ms timeout\n' +
    'Error: Invocation timeout of calling "resolveLiveProtonClientSession" method on "electron-mail:webview-api:primary" channel with 25000ms timeout\n' +
    '    at <anonymous>:795:24\n' +
    '    at Observable.init [as _subscribe] (<anonymous>:3794:35)\n' +
    '    at Observable._trySubscribe (<anonymous>:2822:25)\n' +
    '    at <anonymous>:2816:121\n' +
    '    at errorContext (<anonymous>:7471:16)\n' +
    '    at Observable.subscribe (<anonymous>:2814:65)\n' +
    '    at doInnerSub (<anonymous>:5210:95)\n' +
    '    at outerNext (<anonymous>:5204:40)\n' +
    '    at OperatorSubscriber._this._next (<anonymous>:3896:15)\n' +
    '    at OperatorSubscriber.Subscriber.next (<anonymous>:3157:99)',
  stack: 'Error: Uncaught (in promise): Error: Invocation timeout of calling "resolveLiveProtonClientSession" method on "electron-mail:webview-api:primary" channel with 25000ms timeout\n' +
    'Error: Invocation timeout of calling "resolveLiveProtonClientSession" method on "electron-mail:webview-api:primary" channel with 25000ms timeout\n' +
    '    at <anonymous>:795:24\n' +
    '    at Observable.init [as _subscribe] (<anonymous>:3794:35)\n' +
    '    at Observable._trySubscribe (<anonymous>:2822:25)\n' +
    '    at <anonymous>:2816:121\n' +
    '    at errorContext (<anonymous>:7471:16)\n' +
    '    at Observable.subscribe (<anonymous>:2814:65)\n' +
    '    at doInnerSub (<anonymous>:5210:95)\n' +
    '    at outerNext (<anonymous>:5204:40)\n' +
    '    at OperatorSubscriber._this._next (<anonymous>:3896:15)\n' +
    '    at OperatorSubscriber.Subscriber.next (<anonymous>:3157:99)\n' +
    '    at resolvePromise (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:30296:25)\n' +
    '    at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:30234:15\n' +
    '    at asyncGeneratorStep (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:67139:9)\n' +
    '    at _throw (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:67153:13)\n' +
    '    at ZoneDelegate.invoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29691:164)\n' +
    '    at Object.onInvoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:53558:29)\n' +
    '    at ZoneDelegate.invoke (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29691:52)\n' +
    '    at Zone.run (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29506:41)\n' +
    '    at file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:30338:32\n' +
    '    at ZoneDelegate.invokeTask (file:///app/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29706:177)'
}
[2021-11-26 13:04:05.552] [error] src/web/browser-window/app/app.error-handler.service.ts {
  name: 'Error',
  message: 'Invocation timeout of calling "updateOverlayIcon" method on "electron-mail:ipcMain-api" channel with 25000ms timeout',
  stack: 'Error: Invocation timeout of calling "updateOverlayIcon" method on "electron-mail:ipcMain-api" channel with 25000ms timeout\n' +
    '    at <anonymous>:795:24\n' +
    '    at Observable.init [as _subscribe] (<anonymous>:3794:35)\n' +
    '    at Observable._trySubscribe (<anonymous>:2822:25)\n' +
    '    at <anonymous>:2816:121\n' +
    '    at errorContext (<anonymous>:7471:16)\n' +
    '    at Observable.subscribe (<anonymous>:2814:65)\n' +
    '    at doInnerSub (<anonymous>:5210:95)\n' +
    '    at outerNext (<anonymous>:5204:40)\n' +
    '    at OperatorSubscriber._this._next (<anonymous>:3896:15)\n' +
    '    at OperatorSubscriber.Subscriber.next (<anonymous>:3157:99)'
}

```

</details>

**Comment by vladimiry** [comment]
Looks similar to placed before #311, #349 and #432 issues solution for which was in updating the `flatpak` thing in the system. Maybe try `flatpak update` command first and then if error is still there update the `flatpak` itself.

What is the flatpak version (`flatpak --version`)?

**Comment by Tibladar** [comment]
```
$ flatpak update
Looking for updates…
Nothing to do.

$ flatpak --version
Flatpak 1.12.2
```
