### ISSUE TITLE
Error message on Linux app

### ISSUE THREAD

**Issue by Thouareg** [vladimiry/ElectronMail#476]
Hi,
I have error message with the linux app image, 4.13.2 (but i have too before with 4.13.1).
I use a debian unstable. The messages not appear at the start, but later.

Invocation timeout of calling "dbGetAccountMetadata" method on "electron-mail:ipcMain-api" channel with 25000ms timeout

And several times this :

Uncaught (in promise): Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).
Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).
at file:///tmp/.mount_electrUbjAFi/resources/app.asar/app/web/browser-window/index.mjs:34027:47
at doInnerSub (file:///tmp/.mount_electrUbjAFi/resources/app.asar/app/web/browser-window/index.mjs:27768:68)
at outerNext (file:///tmp/.mount_electrUbjAFi/resources/app.asar/app/web/browser-window/index.mjs:27762:38)
at OperatorSubscriber._this._next (file:///tmp/.mount_electrUbjAFi/resources/app.asar/app/web/browser-window/index.mjs:26507:13)
at OperatorSubscriber.Subscriber.next (file:///tmp/.mount_electrUbjAFi/resources/app.asar/app/web/browser-window/index.mjs:25633:97)
at AsyncAction.<anonymous> (file:///tmp/.mount_electrUbjAFi/resources/app.asar/app/web/browser-window/index.mjs:26434:24)
at AsyncAction._execute (file:///tmp/.mount_electrUbjAFi/resources/app.asar/app/web/browser-window/index.mjs:29637:16)
at AsyncAction.execute (file:///tmp/.mount_electrUbjAFi/resources/app.asar/app/web/browser-window/index.mjs:29630:26)
at AsyncScheduler.flush (file:///tmp/.mount_electrUbjAFi/resources/app.asar/app/web/browser-window/index.mjs:29687:30)
at args.<computed> (file:///tmp/.mount_electrUbjAFi/resources/app.asar/app/web/browser-window/index.mjs:32939:37)

So, if you can sort it out.
I'm not a specialist, so I don't know what's going on.
Good luck, and thank you for your work, this is an application that I really like.

Thouareg

**Comment by vladimiry** [comment]
Flatpak installation?

**Comment by vladimiry** [comment]
There were similar issue with Flatpak package solution for which was in using the recent flatpak version.

The timeouts are extensively used in the app by design in order to spot such kinds of issues. I mean, 25sec is more than enough for the "dbGetAccountMetadata" action, but something in your case stops the app from fulfilling the action and it's likely a system/environment-specific issue, not the app's implementation issues.

So if you want to keep using the app I'd suggest the try another installation package/source, like https://flathub.org/apps/details/com.github.vladimiry.ElectronMail or "deb" file.

**Comment by Thouareg** [comment]
Ok, yes it's a Appimage.
But i used an appimage for month, without have this error before. It's true that both, appimage and system, have evolved over time. So ...

I'll see what I'll do.
Thank you for answering

**Comment by vladimiry** [comment]
> ike https://flathub.org/apps/details/com.github.vladimiry.ElectronMail or "deb" file (I'd choose flatpak option).

Besides, there is https://snapcraft.io/electron-mail option.

**Comment by Thouareg** [comment]
Hi,
So i have installed "deb" file. And same thing : 
![Capture d’écran_2022-01-06_12-59-32](https://user-images.githubusercontent.com/97188589/148380214-a4033418-9abe-485c-b8c5-c6b6d9988546.png)


So the problem exist in appimage, deb file, and i think flatpack too, if i undertstand this : 
https://github.com/vladimiry/ElectronMail/issues/467

I am wondering if the problem comes when the system goes into sleep mode. I use 2 proton accounts, like #467 .

**Comment by vladimiry** [comment]
> So the problem exist in appimage, deb file, and i think flatpack too, if i undertstand this :

You could still try "flatpack" version, and "snap" too. I mean, if you want to use the app.

> I am wondering if the problem comes when the system goes into sleep mode

The "dbGetAccountMetadata" related error techically might but the webview-related error is a one-off action which gets executed once when the proton web client pages gets loaded.

**Comment by vladimiry** [comment]
Moved to #559.
