### ISSUE TITLE
Ubuntu 22.04: electronmail 5.0.2

### ISSUE THREAD

**Issue by pachainti** [vladimiry/ElectronMail#479]
Hi,
I'm using electronmail 4.13.2 on ubuntu 20.04. I have several protonMail accounts and I get many errors:
Electron: 15.3.4
Chromium: 94.0.4606.81
Node: 16.5.0
V8: 9.4.146.21-electron.0

```
Uncaught (in promise): Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).
Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).
at file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:34027:47
at doInnerSub (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:27768:68)
at outerNext (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:27762:38)
at OperatorSubscriber._this._next (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:26507:13)
at OperatorSubscriber.Subscriber.next (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:25633:97)
at AsyncAction.<anonymous> (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:26434:24)
at AsyncAction._execute (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29637:16)
at AsyncAction.execute (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29630:26)
at AsyncScheduler.flush (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:29687:30)
at args.<computed> (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:32939:37)
```

**Comment by vladimiry** [comment]
Flatpak installation?

**Comment by pachainti** [comment]
> Flatpak installation? I'd recommend to explore the following issue: https://github.com/vladimiry/ElectronMail/issues?q=label%3Awebview-load-failed+is%3Aclosed To recap, it's a flatpak/environment-specific issue, not a bug in the app.

You are right, I did not write that I use .deb version.

**Comment by vladimiry** [comment]
If I remember things right this issue was not placed before for ".deb" package. But the answer is the same - something in your system prevent the app from loading the embedded proton page/html (via webview). So I'd recommend to try a Flatpak/Snap/AppImage package version.

**Comment by pachainti** [comment]
> If I remember things right this issue was not placed before for ".deb" package. But the answer remains the same - something in your system prevents the app from loading the embedded proton page/html (via webview). So I'd recommend to try a [Flatpak](https://flathub.org/apps/details/com.github.vladimiry.ElectronMail)/[Snap](https://snapcraft.io/electron-mail/)/AppImage since these package types come with certain level of isolation.

I tried with appimage and the behaviour is the same. So I suspect that even with flatpak/snap will be the same.

**Comment by vladimiry** [comment]
> So I suspect that even with flatpak/snap will be the same.

Not necessary as flatpak/snap comes with a much more extended isolation capabilities in comparison with appimage.

**Comment by pachainti** [comment]
Hi,
on electronmail 5.0.2 on ubuntu 20.04 there are some different errors:
Electron: 19.0.10
Chromium: 102.0.5005.167
Node: 16.14.2
V8: 10.2.154.15-electron.0
Debian package

```
Uncaught (in promise): WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
at file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:8746:83
at Observable.init [as _subscribe] (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4032:33)
at Observable._trySubscribe (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:2948:23)
at file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:2942:119
at errorContext (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:5207:14)
at Observable.subscribe (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:2940:63)
at doInnerSub (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4367:52)
at outerNext (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4361:38)
at OperatorSubscriber._this._next (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4085:13)
at Subscriber.next (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:3219:97)

Unhandled Promise Rejection
Error: Failed index emails in 60000ms (mails portions size: 1000)
    at /opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:94086:50
    at doInnerSub (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:79874:33)
    at outerNext (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:79868:40)
    at OperatorSubscriber._this._next (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:78329:15)
    at Subscriber.next (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:76598:123)
    at AsyncAction.<anonymous> (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:78183:26)
    at AsyncAction._execute (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:82462:18)
    at AsyncAction.execute (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:82455:28)
    at AsyncScheduler.flush (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:82534:32)
    at listOnTimeout (node:internal/timers:559:17)
```

**Comment by vladimiry** [comment]
>  Debian package

Consider trying https://flathub.org/apps/details/com.github.vladimiry.ElectronMail and https://snapcraft.io/electron-mail package types.

**Comment by pachainti** [comment]
> > Debian package
> 
> Consider trying https://flathub.org/apps/details/com.github.vladimiry.ElectronMail and https://snapcraft.io/electron-mail package types.

I have tried appImage, flatpak, different OS and machine and I see no difference.

**Comment by pachainti** [comment]
Hi,
I have upgraded to ubuntu 22.04.1, it seems a bit faster, however the errors are still there:
Electron: 19.0.10
Chromium: 102.0.5005.167
Node: 16.14.2
V8: 10.2.154.15-electron.0

**Comment by vladimiry** [comment]
I'm making some changes for the next release, which might make this issue less annoying.

**Comment by vladimiry** [comment]
Moved to #559.
