### ISSUE TITLE
Linux .deb UnhandledError: Failed index emails in 30000ms (mails portions size: 1000)

### ISSUE THREAD

**Issue by mearlboro** [vladimiry/ElectronMail#494]
Running on Debian unstable (the PureOS version) with Wayland & SwayWM. Installed .deb package. This happens in both ElectronMail 4.13.2 and 4.13.3.
This does not happen when I run ElectronMail on i3WM under X. I tried both with and without the flag `--enable-features=UseOzonePlatform --ozone-platform=wayland` .

```
Unhandled Error
RuntimeError: abort(Error: Failed index emails in 30000ms (mails portions size: 1000)). Build with -s ASSERTIONS=1 for more info.
    at process.C (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:39484:19)
    at process.emit (node:events:406:35)
    at processEmit [as emit] (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:55184:45)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:237:9)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

After the error is displayed and dismissed, the following message

> Invocation timeout of calling "updateOverlayIcon" method on "electron-mail:ipcMain-api" channel with 25000ms timeout

is shown 3 times in the front-end as floating error messages. After I dismiss them I can continue using ElectronMail normally. 

I don't know if this is related to #476. Happy to clarify any other details if needed.

**Comment by vladimiry** [comment]
Thanks for the detailed report. I'd need to run a similar environment in order to reproduce the issue which I'm not going to jump into in the near future.

I'd suggest to try another package type, like Flatpak/Snap (these 2 come with OS isolation capabilities).

**Comment by mearlboro** [comment]
Thanks for the prompt reply, I will try the other package types.

I'm writing more notes here, for other Debian based people using Wayland and Sway. It's a known thing Electron and Wayland are not the bestest of friends, but maybe you can reproduce this in whichever OS as long as the underlying DM is Wayland.

So when running with the wayland flags from the terminal, I get the following 
```
(node:55031) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `electron-mail --trace-deprecation ...` to show where the warning was created)
[55071:0220/175224.552614:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is egl, ANGLE is 
[55071:0220/175224.557176:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:55031) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

and sometimes (but not always) when I try to kill the session (^C) the whole Wayland login session crashes. I can give you some journalctl dumps or any other kind of logs if you let me know what can be of interest.

Many thanks for the great work you put in this project!

**Comment by mearlboro** [comment]
Finally, I wanted to add that after seeing the error in my original posts a few times, I started noticing that the front-end of ElectronMail freezes some times, taking my wayland login session with it when I kill it. It's still in Heisenbug land, I'm afraid.

**Comment by vladimiry** [comment]
> I tried both with and without the flag --enable-features=UseOzonePlatform --ozone-platform=wayland .

Maybe also try other args, like:
- `--disable-gpu-sandbox`
- `--no-sandbox` & `--disable-gpu`
- `--enable-features=Vulkan`

**Comment by pangratt12345** [comment]
hey, in case of application crashing with message "Error: Failed index emails in 30000ms (mails portions size: 112)" after start-up then this method from https://github.com/vladimiry/ElectronMail/issues/727 can fix it
- disabling the “Full-text search” switch in the “General” app settings.
