### ISSUE TITLE
Uncaught (in promise): Error: Failed to wait for "webview" service provider initialization

### ISSUE THREAD

**Issue by GentlyD** [vladimiry/ElectronMail#524]
Thanks for the great app, use it a lot.

Recently, on changing to "settings" I got the error "Uncaught (in promise): Error: Failed to wait for "webview" service provider initialization" (see below)

Happened only once so far. Is it the App or is it the Proton server?

Uncaught (in promise): Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).
Error: Failed to wait for "webview" service provider initialization (timeout: 15000ms).
at file:///C:/Users/xxxxxxxx/AppData/Local/Programs/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:8718:76
at doInnerSub (file:///C:/Users/xxxxxxxx/AppData/Local/Programs/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4375:27)
at outerNext (file:///C:/Users/xxxxxxxx/AppData/Local/Programs/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4369:38)
at OperatorSubscriber._this._next (file:///C:/Users/xxxxxxxx/AppData/Local/Programs/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4093:13)
at OperatorSubscriber.Subscriber.next (file:///C:/Users/xxxxxxxx/AppData/Local/Programs/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:3227:97)
at AsyncAction.<anonymous> (file:///C:/Users/xxxxxxxx/AppData/Local/Programs/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4068:24)
at AsyncAction._execute (file:///C:/Users/xxxxxxxx/AppData/Local/Programs/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4819:16)
at AsyncAction.execute (file:///C:/Users/xxxxxxxx/AppData/Local/Programs/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4812:26)
at AsyncScheduler.flush (file:///C:/Users/xxxxxxxx/AppData/Local/Programs/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4882:30)
at args.<computed> (file:///C:/Users/xxxxxxxx/AppData/Local/Programs/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:7703:37)

**Comment by GentlyD** [comment]
Thanks, it is Windows:

Windows 11 Pro
21H2
22000.708
Windows Feature Experience Pack 1000.22000.708.0

**Comment by myviolinsings** [comment]
I am on  Ubuntu 22.04 and have had no issues till today. First, was ticking some items for deletion in inbox and looked up to see no icons but large "Oops there was an error". So I closed the window, reopened and it was still there; signed out of that account, reentered password, signed back in and error message was gone. But within a few seconds the Uncaught appeared. Clicked out of it and it's working but thought I should update the issue here:
![image](https://user-images.githubusercontent.com/42390999/181354988-b03c9322-7d78-4561-92b5-d90851877d6d.png)
Also of note, I have 2 accounts in Electron and only one had this issue.

**Comment by vladimiry** [comment]
Moved to #559.
