### ISSUE TITLE
electron-mail-5.1.1 deb & appimage - error messages

### ISSUE THREAD

**Issue by hopeless-attempt** [vladimiry/ElectronMail#558]
Just updated from 5.1.0 to 5.1.1, deb.
 5.1.0 was working perfectly but 5.1.1 threw these error messages.
Running MXLinux 21.2.1 KDE Plasma 5.20.5 Debian 11.5.

Uncaught (in promise): WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
at file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:8834:83
at Observable.init [as _subscribe] (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4096:33)
at Observable._trySubscribe (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:2948:23)
at file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:2942:119
at errorContext (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:5289:14)
at Observable.subscribe (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:2940:63)
at doInnerSub (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4423:52)
at outerNext (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4417:38)
at OperatorSubscriber._this._next (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4149:13)
at Subscriber.next (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:3219:97)

Failed to ping the "webview" backend service (timeout: 7006ms).

Uncaught (in promise): WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
at file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:8834:83
at Observable.init [as _subscribe] (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4096:33)
at Observable._trySubscribe (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:2948:23)
at file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:2942:119
at errorContext (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:5289:14)
at Observable.subscribe (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:2940:63)
at doInnerSub (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4423:52)
at outerNext (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4417:38)
at OperatorSubscriber._this._next (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:4149:13)
at Subscriber.next (file:///opt/ElectronMail/resources/app.asar/app/web/browser-window/index.mjs:3219:97)

I'll now try the appimage to see if it's any better.

**Comment by hopeless-attempt** [comment]
Same issue with the appimage.
Have to revert to 5.1.0 for now.

**Comment by vladimiry** [comment]
I didn't make any changes in 5.1.1 related to this timeout (webview loading), but in 5.1.0, so apparently it's coming with @electron update.

> Same issue with the appimage.

Consider trying https://flathub.org/apps/details/com.github.vladimiry.ElectronMail.

**Comment by vladimiry** [comment]
Moved to #559.
