### ISSUE TITLE
Unhandled Error when trying to open Electronmail

### ISSUE THREAD

**Issue by frorayz** [vladimiry/ElectronMail#586]
Hi I am getting these errors on macOS when opening the app. 

```
Unhandled Promise Rejection
Error: Failed index emails in 30000ms (mails portions size: 1000)
    at /Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:88048:50
    at doInnerSub (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:76158:33)
    at outerNext (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:76152:40)
    at OperatorSubscriber._this._next (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:74610:15)
    at Subscriber.next (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:72856:123)
    at AsyncAction.<anonymous> (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:74464:26)
    at AsyncAction._execute (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:78735:18)
    at AsyncAction.execute (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:78728:28)
    at AsyncScheduler.flush (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:78806:32)
    at listOnTimeout (node:internal/timers:559:17)
```

```
Unhandled Error
RuntimeError: abort(Error: Failed index emails in 30000ms (mails portions size: 1000)) at Error
    at /Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:707:23
    at process.z (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:717:14)
    at process.emit (node:events:525:35)
    at process.processEmit [as emit] (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:81457:45)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:269:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:97:32)
    at process.z (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:722:21)
    at process.emit (node:events:525:35)
    at process.processEmit [as emit] (/Applications/ElectronMail.app/Contents/Resources/app.asar/app/electron-main/index.cjs:81457:45)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:269:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:97:32)
```
I am on:
<img width="648" alt="Screen Shot 2023-02-06 at 9 37 12 PM" src="https://user-images.githubusercontent.com/32178410/217133622-ac5cf327-755f-453c-8cb2-18951504b579.png">

**Comment by vladimiry** [comment]
Closing as duplicated of #551.

Handling #571 should prevent this kind of error, as a real database will be doing the indexing.
