### ISSUE TITLE
Error message when opening the app

### ISSUE THREAD

**Issue by BobWs** [vladimiry/ElectronMail#616]
Lately I get this error message every time I open the app. Any idea how I can fix this?

```
Uncaught (in promise): WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
WebviewPingFailedError: Failed to ping the "webview" backend service (timeout: 7000ms).
at file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:8855:83
at Observable.init [as _subscribe] (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4096:33)
at Observable._trySubscribe (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:2948:23)
at file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:2942:119
at errorContext (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:5293:14)
at Observable.subscribe (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:2940:63)
at doInnerSub (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4425:52)
at outerNext (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4419:38)
at OperatorSubscriber._this._next (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:4149:13)
at Subscriber.next (file:///Applications/ElectronMail.app/Contents/Resources/app.asar/app/web/browser-window/index.mjs:3219:97)×
Failed to ping the "webview" backend service (timeout: 7006ms).
```

**Comment by vladimiry** [comment]
This is fixed in the next/5.1.8 release.

You can get a work-in-progress 5.1.8 version with included fix from the link in the https://github.com/vladimiry/ElectronMail/issues/559#issuecomment-1508160458 message.
