### ISSUE TITLE
Failed to decrypt the settings storage

### ISSUE THREAD

**Issue by linuxsucks1** [vladimiry/ElectronMail#646]
[2023-11-06 17:28:29.404] [error] src/electron-main/api/index.ts init "keytar" module is unsupported by the system:  An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.124" (uid=1000 pid=8055 comm="/snap/electron-mail/67/electron-mail --js-flags=--" label="snap.electron-mail.electron-mail (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.24" (uid=1000 pid=4511 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")
[2023-11-07 15:14:06.792] [error] src/electron-main/api/index.ts init "keytar" module is unsupported by the system:  An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.160" (uid=1000 pid=34032 comm="/snap/electron-mail/67/electron-mail --js-flags=--" label="snap.electron-mail.electron-mail (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.19" (uid=1000 pid=4762 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")
[2023-11-07 15:14:23.743] [error] src/electron-main/api/index.ts [pubsub-to-rpc-api] [provider] notification.error {"name":"readSettings","channel":"electron-mail:ipcMain-api","payloadType":"request","uid":"833bc443-5202-4da8-973c-46a00eda1225"} DecryptionError: Decryption failed ({"type":"crypto","options":{"ivBytes":16,"algorithm":"aes-256-cbc"},"data":{"ivBase64":"e+Ma7s8gjo3UF03+h8CgPg=="}})
    at Object.<anonymous> (/snap/electron-mail/67/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:56:35)
    at step (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:176:57)
    at rejected (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:167:69)
[2023-11-07 15:14:23.745] [error] src/electron-main/web-contents.ts {"type":"console-message","level":3,"message":"[object Object]","line":8680,"sourceId":"file:///snap/electron-mail/67/resources/app.asar/app/web/browser-window/index.mjs"}
[2023-11-07 15:14:23.801] [error] src/web/browser-window/app/_options/options.effects.ts DecryptionError: Decryption failed ({"type":"crypto","options":{"ivBytes":16,"algorithm":"aes-256-cbc"},"data":{"ivBase64":"e+Ma7s8gjo3UF03+h8CgPg=="}})
    at Object.<anonymous> (/snap/electron-mail/67/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:56:35)
    at step (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:176:57)
    at rejected (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:167:69) {
  cause: 'Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT'
}
[2023-11-07 15:15:26.618] [error] src/electron-main/api/index.ts [pubsub-to-rpc-api] [provider] notification.error {"name":"readSettings","channel":"electron-mail:ipcMain-api","payloadType":"request","uid":"d24a94b1-dd2e-4ed9-a1d9-834c26c65458"} DecryptionError: Decryption failed ({"type":"crypto","options":{"ivBytes":16,"algorithm":"aes-256-cbc"},"data":{"ivBase64":"e+Ma7s8gjo3UF03+h8CgPg=="}})
    at Object.<anonymous> (/snap/electron-mail/67/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:56:35)
    at step (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:176:57)
    at rejected (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:167:69)
[2023-11-07 15:15:26.627] [error] src/electron-main/web-contents.ts {"type":"console-message","level":3,"message":"[object Object]","line":8680,"sourceId":"file:///snap/electron-mail/67/resources/app.asar/app/web/browser-window/index.mjs"}
[2023-11-07 15:15:26.629] [error] src/web/browser-window/app/_options/options.effects.ts DecryptionError: Decryption failed ({"type":"crypto","options":{"ivBytes":16,"algorithm":"aes-256-cbc"},"data":{"ivBase64":"e+Ma7s8gjo3UF03+h8CgPg=="}})
    at Object.<anonymous> (/snap/electron-mail/67/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:56:35)
    at step (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:176:57)
    at rejected (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:167:69) {
  cause: 'Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT'
}
[2023-11-07 15:15:35.231] [error] src/electron-main/api/index.ts [pubsub-to-rpc-api] [provider] notification.error {"name":"readSettings","channel":"electron-mail:ipcMain-api","payloadType":"request","uid":"72aa46da-019f-4b0e-a8b3-3968f2c58869"} DecryptionError: Decryption failed ({"type":"crypto","options":{"ivBytes":16,"algorithm":"aes-256-cbc"},"data":{"ivBase64":"e+Ma7s8gjo3UF03+h8CgPg=="}})
    at Object.<anonymous> (/snap/electron-mail/67/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:56:35)
    at step (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:176:57)
    at rejected (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:167:69)
[2023-11-07 15:15:35.239] [error] src/electron-main/web-contents.ts {"type":"console-message","level":3,"message":"[object Object]","line":8680,"sourceId":"file:///snap/electron-mail/67/resources/app.asar/app/web/browser-window/index.mjs"}
[2023-11-07 15:15:35.241] [error] src/web/browser-window/app/_options/options.effects.ts DecryptionError: Decryption failed ({"type":"crypto","options":{"ivBytes":16,"algorithm":"aes-256-cbc"},"data":{"ivBase64":"e+Ma7s8gjo3UF03+h8CgPg=="}})
    at Object.<anonymous> (/snap/electron-mail/67/resources/app.asar/node_modules/fs-json-store-encryption-adapter/lib/encryption/index.js:56:35)
    at step (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:195:27)
    at Object.throw (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:176:57)
    at rejected (/snap/electron-mail/67/resources/app.asar/node_modules/tslib/tslib.js:167:69) {
  cause: 'Error: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT'
}

**Comment by vladimiry** [comment]
Two possible reasons. The `settings.bin` file got corrupted for some reason (file purpose described in [FAQ](https://github.com/vladimiry/ElectronMail/wiki/FAQ)) or wrong password used.

**Comment by linuxsucks1** [comment]
It seems the settings.bin doesn't understand Latvian on my linux at this time. So I changed my language to English (my operating system was using it already, but the time, date wasn't) and my master password is now accepted without further changes.

**Comment by vladimiry** [comment]
Closing for now, as there are no planned changes related to this issue.
