### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by babebort** [vladimiry/ElectronMail#708]
`Unhandled Promise Rejection
Error: Failed index emails in 30000ms (mails portions size: 1000)
    at /app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:70313:50
    at doInnerSub (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:61763:33)
    at outerNext (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:61757:40)
    at OperatorSubscriber._this._next (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:60215:15)
    at Subscriber.next (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:58461:123)
    at AsyncAction.<anonymous> (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:60069:26)
    at AsyncAction._execute (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:64334:18)
    at AsyncAction.execute (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:64327:28)
    at AsyncScheduler.flush (/app/ElectronMail/resources/app.asar/app/electron-main/index.cjs:64405:32)`

Didnt open calendar, it was minimised but I git error

**Comment by vladimiry** [comment]
The full-text search is only available when the "local store" feature is enabled for the account. The index is not stored, but gets generated each time the app starts, and then it sits in the memory. I didn't test the feature on a very large number of email messages, but it's clear that the described approach is not suitable for a large data sets.

What you can try to do is increasing the `timeouts.indexingBootstrap` value in the `config.json` file located in the [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg). There is no guarantee that it resolves the issue, so then the “Full-text search” switch could be disabled in the “General” app settings.

The ultimate solution for reducing memory use, speeding up things, and increasing indexing stability is implementing #571 as all the “local store” related needs, like storing and searching, would be handled by SQLite.

There is no other proper solution other than implementing #571, so closing the issue.
