### ISSUE TITLE
When Downloading files from Proton Drive, they do not get locally stored

### ISSUE THREAD

**Issue by mixmegapol** [vladimiry/ElectronMail#722]
When Downloading files from proton drive, I get the following error message. I do not get asked, where this file shall be stored, and I do not see the file stored anywhere in my filesystems.

Unhandled Promise Rejection
Error: Failed to resolve file system resource directory from the "webclient://mail.proton.me/sw/2" request
    at resolveFileSystemResourceLocation (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:75939:57)
    at AsyncFunction.<anonymous> (/opt/ElectronMail/resources/app.asar/app/electron-main/index.cjs:75973:42)

Please advice

Kind regards
Daniel

**Comment by mixmegapol** [comment]
Package: electron-mail-5.3.0-linux-amd64.deb

**Comment by vladimiry** [comment]
Downloading worked fine at my side on 21MB mp3 file. It might be size-dependent, but I didn't test a larger file yet.

**Comment by mixmegapol** [comment]
Thank you. You are right. A single 5MB file worked fine. I just wanted to copy down everything from Proton Drive to my new linux laptop, multiple recursive directories downloaded as a zip file of around 20-50GB sizes.
